apiVersion: 1
  
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    jsonData:
      timeInterval: "30s"
    secureJsonData:
      httpHeaderName1: "X-Custom-Header"  # Optional, only if you need custom headers

